classdef acquisition < handle
    %ACQUISITION
    %   Detailed explanation goes here
    
    properties (Access = public)
        
        
        
        pressure
        modulo
        average
        variance
        med
        
        % move as private after debug
        %ctd            % CTD on serial port
        port = 1
        baudRate = 7   % default 19200
        dataBits = 2   % default 8
        stopBits = 1   % default 1
        parity = 1     % default none
        terminator = 3 % default 'CR/LF'
        station = 'FR28001'
        state          % before or after station
        delay   = '5'  % default, 5 s
        theTimer       % timer set with delay
        path    = 'data'
        xmlFile = 'data/1263.xml'
        
        % files
        rawFileName
        dataFileName
        dataName
        statFileName
        
    end
    
    properties (Access = private)
        % save program configuration in user preference mat file
        configFile = [prefdir, filesep, mfilename, '.mat'];
        
        % define popup string for serial port
        portString         % = us191.serial.Discover
        baudRateString = {'300','600','1200','2400','4800','9600','19200','57600','112000'}
        dataBitsString = {'7','8'}
        stopBitsString = {'1','2'}
        parityString = {'none','even','odd'}
        terminatorString = {'CR','LF','CR/LF'}
        
    end
    
    
    properties (Access = private, SetObservable)
        % Panels
        hdlMainFigure
        hdlConfigPanel
        hdlPanelMeasure
        hdlPanelTreat
        
        % Panel configuration
        hdlStation
        hdlPath
        hdlPathSelect
        hdlCheckboxBefore
        hdlCheckboxAfter
        hdSelectdelay
        hdlXmlFile
        hdlXmlFileSelect
        
        hdlSelectPort
        hdlSelectDatabits
        hdlSelectBaudrate
        hdlSelectStopbits
        hdlSelectParity
        hdlSelectTerminator
        
        
        % Panel acquisition
        hdlButtonStart
        hdlReadPressure
        hdlReadModulo
        
        % Panel results
        hdlReadMedian
        hdlReadVar
        hdlReadMean
        hdlReadStandDev
    end
    
    methods % Public
        
        % Constructor
        function obj = acquisition()
            
            % discover serial port 
            obj.portString = us191.serial.Discover;
            if isempty(obj.portString )
              obj.portString = {'N/A'};
            end
          
            % define GUI
            obj.hdlMainFigure = figure( ...
                'Name','Processing ',...
                'NumberTitle', 'off', ...
                'MenuBar', 'None',...
                'Toolbar', 'None', ...
                'WindowStyle', 'normal', ...
                'numbertitle', 'off',...
                'HandleVisibility','on',...
                'Position',[100 200 700 620],...
                'Color', get( 0, 'DefaultUIControlBackgroundColor'),...
                'CloseRequestFcn', {@(src,evt) delete(obj)});
            
            obj.hdlConfigPanel = uipanel('Parent',obj.hdlMainFigure,...
                'Title','Configuration',...
                'FontSize',12,...
                'Position',[0. .6 1 .4],...
                'FontWeight', 'bold');
            
            obj.hdlPanelMeasure =  uipanel('Parent',obj.hdlMainFigure,...
                'Title','Acquisition',...
                'FontSize',12,...
                'Position',[0. .3 1 .3],...
                'FontWeight', 'bold');
            
            obj.hdlPanelTreat =  uipanel('Parent',obj.hdlMainFigure,...
                'Title','Results',...
                'FontSize',12,...
                'Position',[0. .0 1 .3],...
                'FontWeight', 'bold');
            
            loadConfig(obj);
            obj.setUicontrols;
            
        end % end of constructor
        
        % Destructor
        % ----------
        function delete(obj)
            % method save_config
            saveConfig(obj);
            closereq;
        end
        
        % Fonctions set UIcontrol
        %-----------------------------------------------------
        function setUicontrols(obj)
            
            % Panel Configuration
            % Serial port
            uicontrol ( obj.hdlConfigPanel ,...
                'Style' , 'Text' ,...
                'String' ,'Port' ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position' ,[0.05 0.83 0.1 0.1],...
                'FontWeight', 'bold',...
                'FontSize',9);
            
            obj.hdlSelectPort = uicontrol ( obj.hdlConfigPanel ,...
                'Style' , 'popup' ,...
                'String' , obj.portString ,...
                'Value', obj.port,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position' ,[0.15 0.85 0.1 0.1],...
                'callback', {@(src,evt) selectPort(obj,src)});
            
            uicontrol ( obj.hdlConfigPanel ,...
                'Style' , 'Text' ,...
                'String' ,'Baudrate' ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position' ,[0.05 0.68 0.1 0.1],...
                'FontWeight', 'bold',...
                'FontSize',9 );
            
            obj.hdlSelectBaudrate = uicontrol ( obj.hdlConfigPanel ,...
                'Style' , 'popup' ,...
                'String' ,obj.baudRateString,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position' ,[0.15 0.70 0.1 0.1],...
                'Value',obj.baudRate,...
                'callback', {@(src,evt) selectBaudRate(obj,src)});
            
            uicontrol ( obj.hdlConfigPanel ,...
                'Style' , 'Text' ,...
                'String' ,'Databits' ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position' ,[0.05 0.53 0.1 0.1],...
                'FontWeight', 'bold',...
                'FontSize',9 );
            
            obj.hdlSelectDatabits = uicontrol ( obj.hdlConfigPanel ,...
                'Style' , 'popup' ,...
                'String' , obj.dataBitsString ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Value',obj.dataBits,...
                'Position' ,[0.15 0.55 0.1 0.1],...
                'callback', {@(src,evt) selectDataBits(obj,src)}) ;
            
            uicontrol ( obj.hdlConfigPanel ,...
                'Style' , 'Text' ,...
                'String' ,'Stopbits' , ...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position', [0.05 0.38 0.1 0.1],...
                'FontWeight', 'bold',...
                'FontSize',9 );
            
            obj.hdlSelectStopbits = uicontrol ( obj.hdlConfigPanel ,...
                'Style' , 'popup' ,...
                'String' , obj.stopBitsString ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Value',obj.stopBits,...
                'Position' ,[0.15 0.4 0.1 0.1],...
                'callback', {@(src,evt) selectStopBits(obj,src)});
            
            uicontrol ( obj.hdlConfigPanel ,...
                'Style' , 'Text' ,...
                'String' ,'Parity' , ...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position', [0.05 0.23 0.1 0.1],...
                'FontWeight', 'bold',...
                'FontSize',9 );
            
            obj.hdlSelectParity = uicontrol ( obj.hdlConfigPanel ,...
                'Style' , 'popup' ,...
                'String' , obj.parityString ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Value',obj.parity,...
                'Position' ,[0.15 0.25 0.1 0.1],...
                'callback', {@(src,evt) selectParity(obj,src)});
            
            uicontrol ( obj.hdlConfigPanel ,...
                'Style' , 'Text' ,...
                'String' ,'Terminator' ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position' ,[0.05 0.08 0.1 0.1],...
                'FontWeight', 'bold',...
                'FontSize',9 );
            
            obj.hdlSelectTerminator = uicontrol ( obj.hdlConfigPanel ,...
                'Style' , 'popup' ,...
                'String' , obj.terminatorString,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Value',obj.terminator,...
                'Position' ,[0.15 0.1 0.1 0.1],...
                'callback', {@(src,evt) selectTerminator(obj,src)} );
            
            % software configuration
            % station number
            uicontrol(obj.hdlConfigPanel,...
                'style', 'Text', ...
                 'String', 'Station number',...
                'units', 'normalized',...
                'position', [0.35 0.93 0.15 0.08],...
                'HorizontalAlignment', 'left');
            
            obj.hdlStation = uicontrol(obj.hdlConfigPanel,...
                'style', 'edit', ...
                'string', obj.station, ...
                'units', 'normalized', ...
                'position', [0.35 0.83 0.13 0.09], ...
                'callback', {@(src,evt) selectStation(obj)});
              
            % path for data files
             uicontrol(obj.hdlConfigPanel,...
                'style', 'Text', ...
                'String', 'Path for data files',...
                'units', 'normalized',...
                'position', [0.35 0.68 0.45 0.1],...
                'HorizontalAlignment', 'left');
            
            obj.hdlPath = uicontrol(obj.hdlConfigPanel,...
                'style', 'edit', ...
                'units', 'normalized', ...
                'position', [0.35 0.60 0.5 0.10], ...
                'tag', 'PATH', ...
                'string', obj.path, ...
                'HorizontalAlignment', 'left',...
                'TooltipString', 'path for acquisition files .hex, .cnv .asc');
            
            obj.hdlPathSelect = uicontrol(obj.hdlConfigPanel,...
                'string', 'Select', ...
                'units', 'normalized', ...
                'position', [0.88 0.60 0.10 0.1], ...
                'tag', 'PATH_SELECT', ...
                'callback', {@(src,evt) selectPath(obj)});
            
            % CheckBox
            if strcmp(obj.state, 'before')
                value = 1;
            else
                value = 0;
            end
            obj.hdlCheckboxBefore = uicontrol( obj.hdlConfigPanel ,...
                'style' , 'checkbox' ,...
                'String' , ' Before profil',...
                'value', value,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position', [0.35 0.48 0.2 0.1] ,...
                'FontSize',10,...
                'callback', {@(src,evt) selectBeforeStation(obj,src)});
            
            if strcmp(obj.state, 'after')
                value = 1;
            else
                value = 0;
            end
            obj.hdlCheckboxAfter = uicontrol( obj.hdlConfigPanel , ...
                'style' , 'checkbox' ,...
                'String' , ' After profil',...
                'value', value,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position' ,[0.35 0.35 0.2 0.1] ,...
                'FontSize',10, ...
                'callback', {@(src,evt) selectAfterStation(obj,src)});
            
            % timer
            uicontrol( obj.hdlConfigPanel ,...
                'style' , 'Text' ,...
                'String' ,' Timer (s) ' ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position' , [0.55 0.34 0.1 0.1],...
                'FontSize',10);
            
            obj.hdSelectdelay = uicontrol ( obj.hdlConfigPanel ,...
                'style' , ' edit' ,...
                'string', obj.delay,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'BackGroundcolor','w',...
                'position', [0.65 0.35 0.1 0.1],...
                'callback', {@(src,evt) selectTimer(obj,src)});
            
            % xml file
            uicontrol(obj.hdlConfigPanel,...
                'style', 'Text', ...
                'String', 'Sbebird XML config file',...
                'units', 'normalized',...
                'position', [0.35 0.18 0.45 0.1],...
                'HorizontalAlignment', 'left');
            
            obj.hdlXmlFile = uicontrol(obj.hdlConfigPanel,...
                'style', 'edit', ...
                'units', 'normalized', ...
                'position', [0.35 0.10 0.5 0.10], ...
                'tag', 'XMLFILE', ...
                'string', obj.xmlFile, ...
                'HorizontalAlignment', 'left',...
                'TooltipString', 'XML configuration file .xml');
            
            obj.hdlXmlFileSelect = uicontrol(obj.hdlConfigPanel,...
                'string', 'Select', ...
                'units', 'normalized', ...
                'position', [0.88 0.10 0.10 0.1], ...
                'tag', 'XMLFILE_SELECT', ...
                'callback', {@(src,evt) selectXmlFile(obj)});
            
            % Uicontrol Panel acquisition
            %-------------------------------------------------
            
            % Start
            uicontrol(obj.hdlPanelMeasure ,...
                'style' , 'Text' , ...
                'String' ,'Acquisition' ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position' , [0.05 0.80 0.2 0.1] ,...
                'FontWeight', 'bold',...
                'FontSize',10  );
            
            obj.hdlButtonStart = uicontrol (obj.hdlPanelMeasure ,...
                'style' , 'push' ,...
                'string' , 'START',...
                'userdata', false,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'position' , [0.05 0.40 0.2 0.3 ] ,...
                'BackgroundColor', 'r',...
                'FontWeight', 'bold',...
                'callback', {@(src,evt) startAcquisition(obj,src)});
            
            uicontrol( obj.hdlPanelMeasure ,...
                'style' , 'Text' ,...
                'String' ,' Pressure ' ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position' , [0.45 0.7 0.2 0.1] ,...
                'FontWeight', 'bold',...
                'FontSize',10);
            
            obj.hdlReadPressure = uicontrol ( obj.hdlPanelMeasure ,...
                'style' , ' text' ,...
                'String', obj.pressure,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'position', [0.4 0.50 0.2 0.18] ...
                ,'BackGroundcolor','w' );
            
            
            uicontrol( obj.hdlPanelMeasure ,...
                'style' , 'Text' ,...
                'String' ,' db ' ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position' , [0.61 0.52 0.1 0.1] ,...
                'FontWeight', 'bold',...
                'FontSize',10);
            
            
            uicontrol( obj.hdlPanelMeasure  ,...
                'style' , 'Text' ,...
                'String' ,' Modulo ' ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position' , [0.45 0.3 0.2 0.1] ,...
                'FontWeight', 'bold',...
                'FontSize',10);
            
            obj.hdlReadModulo = uicontrol ( obj.hdlPanelMeasure  ,...
                'style' , ' text' ,...
                'String',obj.modulo,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'position', [0.4 0.1 0.2 0.18] ,...
                'BackGroundcolor','w' );
            
            % Uicontrol Panel results
            % ------------------------
            uicontrol( obj.hdlPanelTreat  ,...
                'style' , 'Text' ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'position',[0.05 0.70 0.2 0.1]  ,...
                'String' ,' Mean ' ,...
                'FontWeight', 'bold',...
                'FontSize',10);
            
            obj.hdlReadMean = uicontrol ( obj.hdlPanelTreat ,...
                'style' , 'Text' ,...
                'String', obj.average,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'BackGroundcolor','w',...
                'position' , [0.05 0.45 0.15 0.18] );
            
            
            uicontrol( obj.hdlPanelTreat  ,...
                'style' , 'Text' ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position', [0.3 0.70 0.2 0.1] ,...
                'String' ,' Median ' ,...
                'FontWeight', 'bold',...
                'FontSize',10 );
            
            obj.hdlReadMedian = uicontrol ( obj.hdlPanelTreat ,...
                'style' , 'Text' ,...
                'String',obj.med,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'BackGroundcolor','w',...
                'position' , [0.3 0.45 0.15 0.18] );
            
            uicontrol( obj.hdlPanelTreat  ,...
                'style' , 'Text' , ...
                'String' ,' Variance ' ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position' ,[0.55 0.70 0.2 0.1] ,...
                'FontWeight', 'bold',...
                'FontSize',10 );
            
            obj.hdlReadVar = uicontrol ( obj.hdlPanelTreat ,...
                'style' , 'Text' ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'BackGroundcolor','w',...
                'String',obj.variance,...
                'position' , [0.55 0.45 0.15 0.18]  );
            
            uicontrol( obj.hdlPanelTreat  ,...
                'style' , 'Text' ,...
                'String' ,' Standard deviation ' ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'Position' ,[0.8 0.70 0.2 0.1] ,...
                'FontWeight', 'bold',...
                'FontSize',10 );
            
            obj.hdlReadStandDev = uicontrol ( obj.hdlPanelTreat ,...
                'style' , 'Text' ,...
                'units', 'normalized', ...
                'HorizontalAlignment', 'left',...
                'BackGroundcolor','w',...
                'position' , [0.8 0.45 0.15 0.18]);
            
        end % end of setUicontrols
        
        % callback select value from uicontrols
        % --------------------------------------
        function selectPort(obj, src)
            obj.port =  get(src, 'Value');
        end
        
        function selectBaudRate(obj, src)
            obj.baudRate =  get(src, 'value');
        end
        
        function selectDataBits(obj, src)
            obj.dataBits =  get(src, 'value');
        end
        
        function selectStopBits(obj, src)
            obj.stopBits =  get(src, 'value');
        end
        
        function selectParity(obj, src)
            obj.parity =  get(src, 'value');
        end
        
        function selectTerminator(obj, src)
            obj.terminator =  get(src, 'value');
        end
        
        function selectStation(obj, src)
            obj.station =  get(src, 'value');
        end
        
        function selectTimer(obj, src)
            obj.delay =  get(src, 'string');
        end
        
        
        function selectBeforeStation(obj,src)
            if get(src, 'value')
                obj.state =  'before';
                set(obj.hdlCheckboxAfter,'value',0);
            else
                set(src, 'value', 1);
            end
        end
        
        function selectAfterStation(obj,src)
          if get(src, 'value')
            obj.state =  'after';
            set(obj.hdlCheckboxBefore,'value',0);
          else
            set(src, 'value', 1);
          end
        end
        
        function selectPath(obj)
          obj.path = uigetdir();
          % when cancel is pressed uigetdir return 0
          if obj.path == 0; obj.path = []; end
          set(obj.hdlPath, 'string', obj.path);
        end
        
        function selectXmlFile(obj)
          [FileName,PathName] = uigetfile('*.xml','Select Seabird xml file');
          obj.xmlFile = fullfile(PathName, FileName);
          % when cancel is pressed uigetfile return 0
          if obj.xmlFile == 0; obj.xmlFile = []; end
          set(obj.hdlXmlFile, 'string', obj.xmlFile);
        end
        
        % start acquisition
        function startAcquisition(obj, src)
            % Get date in all file name
            %             FileName = datestr(now);
            %             obj.rawFileName = fprintf('%s.hex',FileName) ;
            %             obj.dataFileName = fprintf('%s.cnv',FileName) ;
            %             obj.dataName = fprintf('%s.cnv',FileName);
            %             obj.statFileName = fprintf('%s.mat',FileName);
            
            % get serial port parameters from uicontrol choices
            
            % change buttun text
            if get(src, 'userdata') == false
                set(src, 'String', 'Initializing...');
                set(src, 'UserData', true);
                
                % get serial port value from popup indice
                theSerialPort = obj.portString{obj.port};
                theBaudRate = str2double(obj.baudRateString{obj.baudRate});
                theDataBits = str2double(obj.dataBitsString{obj.dataBits});
                theStopBits = str2double(obj.stopBitsString{obj.stopBits});
                theParity = obj.parityString{obj.parity};
                theTerminator = obj.terminatorString{obj.terminator};
                
                % Start acquisition
                ctd = us191.ctd(obj.xmlFile,theSerialPort,'baudrate',theBaudRate,...
                    'databits', theDataBits, 'stopbits', theStopBits, ...
                    'parity', theParity, 'terminator',theTerminator);
                
                % define ctd files
                ctd.rawFileName = strcat(obj.path,filesep,obj.station, '.hex');
                ctd.dataFileName = strcat(obj.path,filesep,obj.station, '.cnv');
                
                % open serial port and send commands to the deck-unit
                ctd.open;
                
                % start the timer and callback for acquisition
                t = timer;
                t.StartDelay = str2double(obj.delay);
                t.TimerFcn = {@obj.stopAcquisition, src, ctd};
                t.StartFcn = {@obj.changeButtonStartToGreen, src};
                t.StopFcn = {@obj.changeButtonStartToRed, src};
                start(t);
            end
        end
        
        % stop acquisition
        function stopAcquisition(obj,t,~,src, ctd)
            set(src, 'UserData', false);
            fprintf(1,'timer elapsed after delay: %s sec\n', obj.delay);
            stop(t);
            delete(t);
            close(ctd);
        end
        
        % TODOS: change on anonymous function
        function changeButtonStartToGreen(obj,t,~,src) %#ok<INUSL>
            set(src,'BackgroundColor', 'g');
            set(src, 'String', 'Running...');
        end
        
         % TODOS: change on anonymous function
        function changeButtonStartToRed(obj,t,~,src) %#ok<INUSL>
            set(src,'BackgroundColor', 'r');
            set(src, 'String', 'Start');
        end
        
        % call from close figure
        function s = saveConfig(obj)
            
            % save property values in struct
            s.port = obj.port;
            s.baudRate = obj.baudRate;
            s.dataBits = obj.dataBits;
            s.stopBits = obj.stopBits;
            s.terminator = obj.terminator;
            s.station = obj.station;
            s.state = obj.state;
            s.delay = obj.delay;
            s.path = obj.path;
            s.xmlFile = obj.xmlFile;
            
            % save to mat file
            save( obj.configFile, 's', '-v7.3')
            
        end % end of saveConfig
        
        % restore the configuration from user.mat
        function loadConfig(obj)
            
            % create a struct from public properties of the class
            theConfig = saveToStruct(obj);
            
            % test if configFile exist
            if exist(obj.configFile, 'file') == 2
                % load properties values from struct
                load(obj.configFile, 's');
                props = fieldnames(theConfig);
                for p = 1:numel(props)
                    if  isfield(s, props{p})
                        obj.(props{p}) = s.(props{p});
                    end
                end
            end
            
        end % end of loadConfig
        
    end % end of public methods
    
    methods (Access = private)
        
        % use this function instead of struct(obj)
        % ----------------------------------------
        function s = saveToStruct(obj)
            props = properties(obj);
            for p = 1:numel(props)
                s.(props{p}) = obj.(props{p});
            end
        end % end of saveToStruct
        
    end % end of  private methods
    
    
end

