classdef acquisition < handle
  %ACQUISITION
  %     The purpose of this program is to read CTD pressure value on deck
  %     before and after profil with a CTD SBE911+ to evaluate sensor drift and
  %     hysterisis and then calculate with the atmospheric barometric pressure
  %     the pressure sensor offset.
  %     This program read hex data from a deck-unit SBE11 fron a serial
  %     port, extract the pressure and temperature compensation from the
  %     hexadecimal sentence at 24 hz per seconde and save raw data in files.
  %     All pressure value are stored in a a circular buffer of size 24,
  %     and every second, a timer get the median pressure and store it to a
  %     circular buffer with the size of the acquisition timer (delay).
  %
  %  Jacques Grelet IRD US191 IMAGO
  %  Morganne Domenge
  %  IRD - Campagne PIRATA-FR28 - march 2018
  
  properties (Access = public)
    
    VERSION = '0.13';
    
    % list of public or private properties to save in config mat file
    propertiesToSave = {'VERSION',...
      'port','baudRate','dataBits','stopBits','terminator',...
      'portSbe35','baudRateSbe35','dataBitsSbe35','stopBitsSbe35','terminatorSbe35',...
      'ctdHeight','baroHeight',...
      'station','state','delay','path','xmlFile'};
    
    % ring for averaging every second
    ringAvg = ring(23)
    % timer every second for averaging data
    timerAvg
    % ring with acquisition delay
    ringFinal
    
    
    station = 'TEST'
    state   = 'before'      % before or after station
    delay   = 10  % default, 5 s
    path    = 'data'
    xmlFile = 'data/1263.xml'
    
    % files
    statFileName
    
  end
  
  properties (Access = private)
    % save program configuration in user preference mat file
    configFile = [prefdir, filesep, mfilename, '.mat'];
    
    % define popup string for serial port
    portString         % = us191.serial.Discover
    baudRateString = {'300','600','1200','2400','4800','9600','19200','57600','112000'}
    dataBitsString = {'7','8'}
    stopBitsString = {'1','2'}
    parityString = {'none','even','odd'}
    terminatorString = {'CR','LF','CR/LF'}
    
    % move as private after debug
    port = 1
    baudRate = 7   % default 19200
    dataBits = 2   % default 8
    stopBits = 1   % default 1
    parity = 1     % default none
    terminator = 3 % default 'CR/LF'
    portSbe35 = 1
    baudRateSbe35 = 7   % default 19200
    dataBitsSbe35 = 2   % default 8
    stopBitsSbe35 = 1   % default 1
    paritySbe35 = 1     % default none
    terminatorSbe35 = 3 % default 'CR/LF'
    
    % constants for Thalassa
    ctdHeight = 3.5
    baroHeight = 7.8
    
    % value enter by user at each profil
    pressureBaro
    tAir
    
    % hable for listener 'dataAvailable'
    dataListenerHandle
    
  end
  
  
  properties (Access = private, SetObservable)
    % Panels
    hdlMainFigure
    hdlConfigPanel
    hdlPanelMeasure
    hdlPanelResults
    
    % Panel configuration
    hdlStation
    hdlSelectBaro
    hdlSelectTair
    hdlPath
    hdlPathSelect
    hdlCheckboxBefore
    hdlCheckboxAfter
    hdSelectdelay
    hdlXmlFile
    hdlXmlFileSelect
    
    hdlOptions
    hdlSelectPort
    hdlSelectDatabits
    hdlSelectBaudrate
    hdlSelectStopbits
    hdlSelectParity
    hdlSelectTerminator
    hdlSelectPortSbe35
    hdlSelectDatabitsSbe35
    hdlSelectBaudrateSbe35
    hdlSelectStopbitsSbe35
    hdlSelectParitySbe35
    hdlSelectTerminatorSbe35
    
    hdlSelectCtdHeight
    hdlSelectBaroHeight
    
    
    % Panel acquisition
    hdlButtonStart
    hdlPressure
    hdlFrequency
    hdlTemperature
    hdlModulo
    
    % Panel results
    hdlMedian
    hdlVar
    hdlMean
    hdlStandDev
    hdlOffset
  end
  
  events
    dataAvailable
  end
  
  methods % Public
    
    % Constructor
    function obj = acquisition()
      
      % discover serial port
      obj.portString = us191.serial.Discover;
      if isempty(obj.portString )
        obj.portString = {'N/A'};
      end
      
      % define GUI
      obj.hdlMainFigure = figure( ...
        'Name','Processing ',...
        'NumberTitle', 'off', ...
        'MenuBar', 'None',...
        'Toolbar', 'None', ...
        'WindowStyle', 'normal', ...
        'numbertitle', 'off',...
        'HandleVisibility','on',...
        'Position',[100 200 700 620],...
        'Color', get( 0, 'DefaultUIControlBackgroundColor'),...
        'CloseRequestFcn', {@(src,evt) delete(obj)});
      
      obj.hdlConfigPanel = uipanel('Parent',obj.hdlMainFigure,...
        'Title','Configuration',...
        'FontSize',12,...
        'Position',[0. .6 1 .4],...
        'FontWeight', 'bold');
      
      obj.hdlPanelMeasure =  uipanel('Parent',obj.hdlMainFigure,...
        'Title','Acquisition',...
        'FontSize',12,...
        'Position',[0. .3 1 .3],...
        'FontWeight', 'bold');
      
      obj.hdlPanelResults =  uipanel('Parent',obj.hdlMainFigure,...
        'Title','Results',...
        'FontSize',12,...
        'Position',[0. .0 1 .3],...
        'FontWeight', 'bold');
      
      loadConfig(obj);
      obj.setUiMenus;
      obj.setUicontrols;
      
      % if file is created, set checkbox to 'after', 'before' if not
      obj.statFileName = strcat(obj.path,filesep, obj.station, '.asc');
      if exist(obj.statFileName, 'file')
        obj.state = 'after';
        set(obj.hdlCheckboxAfter,'Value',1);
      else
        obj.state = 'before';
        set(obj.hdlCheckboxBefore,'Value',1);
      end
      
      
    end % end of constructor
    
    % Destructor
    % ----------
    function delete(obj)
      % method save_config
      saveConfig(obj);
      closereq;
    end
    
    % Fonctions set UIcontrol
    %-----------------------------------------------------
    function setUiMenus(obj)
      uimenu(...
        'Parent', obj.hdlMainFigure,...
        'HandleVisibility', 'on',...
        'Label', 'Options',...
        'Callback', {@(src,evt) menuOptions(obj)});
    end
    
    % Fonctions set UIcontrol
    %-----------------------------------------------------
    function setUicontrols(obj)
      
      % software configuration
      
      % left alignement on panel configuration
      leftAlign = 0.05;
      
      % station number
      uicontrol(obj.hdlConfigPanel,...
        'style', 'Text', ...
        'String', 'Station number',...
        'units', 'normalized',...
        'position', [leftAlign 0.92 0.15 0.08],...
        'HorizontalAlignment', 'left');
      
      obj.hdlStation = uicontrol(obj.hdlConfigPanel,...
        'style', 'edit', ...
        'string', obj.station, ...
        'units', 'normalized', ...
        'position', [leftAlign 0.83 0.13 0.09], ...
        'callback', {@(src,evt) selectStation(obj,src)});
      
      leftOffset = 0.2;
      uicontrol(obj.hdlConfigPanel,...
        'style', 'Text', ...
        'String', 'Barometric pressure',...
        'units', 'normalized',...
        'position', [leftAlign+leftOffset 0.92 0.15 0.08],...
        'HorizontalAlignment', 'left');
      
      obj.hdlSelectBaro = uicontrol(obj.hdlConfigPanel,...
        'style', 'edit', ...
        'string', num2str(obj.pressureBaro), ...
        'units', 'normalized', ...
        'position', [leftAlign+leftOffset 0.83 0.13 0.09], ...
        'callback', {@(src,evt) selectPressureBaro(obj,src)});
      
      leftOffset = 0.4;
      uicontrol(obj.hdlConfigPanel,...
        'style', 'Text', ...
        'String', 'Air temperature',...
        'units', 'normalized',...
        'position', [leftAlign+leftOffset 0.92 0.15 0.08],...
        'HorizontalAlignment', 'left');
      
      obj.hdlSelectTair = uicontrol(obj.hdlConfigPanel,...
        'style', 'edit', ...
        'string', num2str(obj.tAir), ...
        'units', 'normalized', ...
        'position', [leftAlign+leftOffset 0.83 0.13 0.09], ...
        'callback', {@(src,evt) selectTair(obj,src)});
      
      % path for data files
      uicontrol(obj.hdlConfigPanel,...
        'style', 'Text', ...
        'String', 'Path for data files',...
        'units', 'normalized',...
        'position', [leftAlign 0.68 0.45 0.1],...
        'HorizontalAlignment', 'left');
      
      obj.hdlPath = uicontrol(obj.hdlConfigPanel,...
        'style', 'edit', ...
        'units', 'normalized', ...
        'position', [leftAlign 0.60 0.68 0.10], ...
        'tag', 'PATH', ...
        'string', obj.path, ...
        'HorizontalAlignment', 'left',...
        'TooltipString', 'path for acquisition files .hex, .cnv .asc');
      
      obj.hdlPathSelect = uicontrol(obj.hdlConfigPanel,...
        'string', 'Select', ...
        'units', 'normalized', ...
        'position', [leftAlign+0.7 0.60 0.10 0.1], ...
        'tag', 'PATH_SELECT', ...
        'callback', {@(src,evt) selectPath(obj)});
      
      % Radio buton group
      bg = uibuttongroup(obj.hdlConfigPanel ,...
        'Visible','on',...
        'units', 'normalized', ...
        'Position',[leftAlign 0.32 .18 .26],...
        'SelectionChangedFcn',{@(src,evt) selectBeforeAfterStation(obj,src,evt)});
      
      if strcmp(obj.state, 'before')
        before.value = 1;
        after.value = 0;
      else
        before.value = 0;
        after.value = 1;
      end
      
      obj.hdlCheckboxBefore = uicontrol( bg ,...
        'style' , 'radiobutton' ,...
        'String' , ' Before profil',...
        'value', before.value,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position', [leftAlign 0.6 0.9 0.4] ,...
        'FontSize',10);
      
      obj.hdlCheckboxAfter = uicontrol( bg , ...
        'style' , 'radiobutton' ,...
        'String' , ' After profil',...
        'value', after.value,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[leftAlign 0.11 0.9 0.4] ,...
        'FontSize',10);
      
      % timer
      uicontrol( obj.hdlConfigPanel ,...
        'style' , 'Text' ,...
        'String' ,' Timer (s) ' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' , [leftAlign+0.2 0.34 0.1 0.1],...
        'FontSize',10);
      
      obj.hdSelectdelay = uicontrol ( obj.hdlConfigPanel ,...
        'style' , ' edit' ,...
        'string', num2str(obj.delay),...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'BackGroundcolor','w',...
        'position', [leftAlign+0.3 0.35 0.1 0.1],...
        'callback', {@(src,evt) selectTimer(obj,src)});
      
      % xml file
      uicontrol(obj.hdlConfigPanel,...
        'style', 'Text', ...
        'String', 'Sbebird XML config file',...
        'units', 'normalized',...
        'position', [leftAlign 0.18 0.45 0.1],...
        'HorizontalAlignment', 'left');
      
      obj.hdlXmlFile = uicontrol(obj.hdlConfigPanel,...
        'style', 'edit', ...
        'units', 'normalized', ...
        'position', [leftAlign 0.10 0.68 0.10], ...
        'tag', 'XMLFILE', ...
        'string', obj.xmlFile, ...
        'HorizontalAlignment', 'left',...
        'TooltipString', 'XML configuration file .xml');
      
      obj.hdlXmlFileSelect = uicontrol(obj.hdlConfigPanel,...
        'string', 'Select', ...
        'units', 'normalized', ...
        'position', [leftAlign+0.7 0.10 0.10 0.1], ...
        'tag', 'XMLFILE_SELECT', ...
        'callback', {@(src,evt) selectXmlFile(obj)});
      
      % Uicontrol Panel acquisition
      %-------------------------------------------------
      
      % Start
      uicontrol(obj.hdlPanelMeasure ,...
        'style' , 'Text' , ...
        'String' ,'Acquisition' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' , [0.05 0.80 0.2 0.1] ,...
        'FontWeight', 'bold',...
        'FontSize',10  );
      
      obj.hdlButtonStart = uicontrol (obj.hdlPanelMeasure ,...
        'style' , 'push' ,...
        'string' , 'START',...
        'userdata', false,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'position' , [0.05 0.40 0.2 0.3 ] ,...
        'BackgroundColor', 'r',...
        'FontWeight', 'bold',...
        'callback', {@(src,evt) startAcquisition(obj,src)});
      
      uicontrol( obj.hdlPanelMeasure ,...
        'style' , 'Text' ,...
        'String' ,' Pressure ' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' , [0.35 0.8 0.2 0.1] ,...
        'FontWeight', 'bold',...
        'FontSize',10);
      
      obj.hdlPressure = uicontrol ( obj.hdlPanelMeasure ,...
        'style' , ' text' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'position', [0.35 0.6 0.2 0.15], ...
        'FontSize',12,...
        'BackGroundcolor','w' );
      
      
      uicontrol( obj.hdlPanelMeasure ,...
        'style' , 'Text' ,...
        'String' ,' db ' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' , [0.55 0.63 0.1 0.1] ,...
        'FontWeight', 'bold',...
        'FontSize',10);
      
      uicontrol( obj.hdlPanelMeasure  ,...
        'style' , 'Text' ,...
        'String' ,'Pressure temperature' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' , [0.35 0.3 0.30 0.1] ,...
        'FontWeight', 'bold',...
        'FontSize',10);
      
      obj.hdlTemperature = uicontrol ( obj.hdlPanelMeasure  ,...
        'style' , ' text' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'position', [0.35 0.1 0.2 0.15] ,...
        'FontSize',12,...
        'BackGroundcolor','w' );
      
      uicontrol( obj.hdlPanelMeasure ,...
        'style' , 'Text' ,...
        'String' ,'Frequency ' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' , [0.70 0.8 0.2 0.1] ,...
        'FontWeight', 'bold',...
        'FontSize',10);
      
      obj.hdlFrequency = uicontrol ( obj.hdlPanelMeasure ,...
        'style' , ' text' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'position', [0.70 0.6 0.2 0.15],...
        'FontSize',12,...
        'BackGroundcolor','w' );
      
      uicontrol( obj.hdlPanelMeasure  ,...
        'style' , 'Text' ,...
        'String' ,'Modulo ' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' , [0.70 0.3 0.2 0.1] ,...
        'FontWeight', 'bold',...
        'FontSize',10);
      
      obj.hdlModulo = uicontrol ( obj.hdlPanelMeasure  ,...
        'style' , ' text' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'position', [0.70 0.1 0.2 0.15] ,...
        'FontSize',12,...
        'BackGroundcolor','w' );
      
      % Uicontrol Panel results
      % ------------------------
      uicontrol( obj.hdlPanelResults  ,...
        'style' , 'Text' ,...
        'String' ,' Mean ' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'position',[0.05 0.75 0.2 0.1]  ,...
        'FontWeight', 'bold',...
        'FontSize',10);
      
      obj.hdlMean = uicontrol ( obj.hdlPanelResults ,...
        'style' , 'Text' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'BackGroundcolor','w',...
        'FontSize',12,...
        'position' , [0.05 0.50 0.15 0.18] );
      
      
      uicontrol( obj.hdlPanelResults  ,...
        'style' , 'Text' ,...
        'String' ,' Median ' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position', [0.3 0.75 0.2 0.1] ,...
        'FontWeight', 'bold',...
        'FontSize',10 );
      
      obj.hdlMedian = uicontrol ( obj.hdlPanelResults ,...
        'style' , 'Text' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'BackGroundcolor','w',...
        'FontSize',12,...
        'position' , [0.3 0.5 0.15 0.18] );
      
      uicontrol( obj.hdlPanelResults  ,...
        'style' , 'Text' , ...
        'String' ,' Variance ' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.55 0.75 0.2 0.1] ,...
        'FontWeight', 'bold',...
        'FontSize',10 );
      
      obj.hdlVar = uicontrol ( obj.hdlPanelResults ,...
        'style' , 'Text' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'BackGroundcolor','w',...
        'FontSize',12,...
        'position' , [0.55 0.5 0.15 0.18]  );
      
      uicontrol( obj.hdlPanelResults  ,...
        'style' , 'Text' ,...
        'String' ,' Standard deviation ' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.8 0.75 0.2 0.1] ,...
        'FontWeight', 'bold',...
        'FontSize',10 );
      
      obj.hdlStandDev = uicontrol ( obj.hdlPanelResults ,...
        'style' , 'Text' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'BackGroundcolor','w',...
        'FontSize',12,...
        'position' , [0.8 0.5 0.15 0.18]);
      
      uicontrol( obj.hdlPanelResults  ,...
        'style' , 'Text' ,...
        'String' ,' Offset ' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'position',[0.05 0.35 0.2 0.1]  ,...
        'FontWeight', 'bold',...
        'FontSize',10);
      
      obj.hdlOffset = uicontrol ( obj.hdlPanelResults ,...
        'style' , 'Text' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'BackGroundcolor','w',...
        'FontSize',12,...
        'position' , [0.05 0.10 0.15 0.18] );
      
    end % end of setUicontrols
    
    % display acquisition object
    % ---------------------
    function disp(obj)
      
      % display properties
      % ------------------
      fprintf('  Version:       ''%s''\n',  obj.VERSION);
      fprintf('  delay:            %2d\n',   obj.delay);
      fprintf('  ctdHeight:       %3.1f\n', obj.ctdHeight);
      fprintf('  baroHeight:      %3.1f\n', obj.baroHeight);
      fprintf('  pressureBaro: %6.1f\n', obj.pressureBaro);
      fprintf('  tair:           %4.1f\n', obj.tAir);     
      
      fprintf('\n');
    end
    
    % callback select value from uicontrols
    % --------------------------------------
    function selectPort(obj, src)
      obj.port =  get(src, 'Value');
    end
    
    function selectBaudRate(obj, src)
      obj.baudRate =  get(src, 'value');
    end
    
    function selectDataBits(obj, src)
      obj.dataBits =  get(src, 'value');
    end
    
    function selectStopBits(obj, src)
      obj.stopBits =  get(src, 'value');
    end
    
    function selectParity(obj, src)
      obj.parity =  get(src, 'value');
    end
    
    function selectTerminator(obj, src)
      obj.terminator =  get(src, 'value');
    end
    
    function selectPortSbe35(obj, src)
      obj.portSbe35 =  get(src, 'Value');
    end
    
    function selectBaudRateSbe35(obj, src)
      obj.baudRateSbe35 =  get(src, 'value');
    end
    
    function selectDataBitsSbe35(obj, src)
      obj.dataBitsSbe35 =  get(src, 'value');
    end
    
    function selectStopBitsSbe35(obj, src)
      obj.stopBitsSbe35 =  get(src, 'value');
    end
    
    function selectParitySbe35(obj, src)
      obj.paritySbe35 =  get(src, 'value');
    end
    
    function selectTerminatorSbe35(obj, src)
      obj.terminatorSbe35 =  get(src, 'value');
    end
    
    % main figure
    function selectStation(obj, src)
      obj.station =  get(src, 'string');
      obj.statFileName = strcat(obj.path,filesep, obj.station, '.asc');
      if exist(obj.statFileName, 'file')
        obj.state = 'after';
        set(obj.hdlCheckboxAfter,'Value',1);
      else
        obj.state = 'before';
        set(obj.hdlCheckboxBefore,'Value',1);
      end
    end
    
    function selectPressureBaro(obj, src)
      obj.pressureBaro =  str2double(get(src, 'string'));
    end
    
    function selectTair(obj, src)
      obj.tAir =  str2double(get(src, 'string'));
    end
    
    function selectTimer(obj, src)
      obj.delay =  str2double(get(src, 'string'));
    end
    
    function selectBeforeAfterStation(obj,~,evt)
      if evt.NewValue.Value && strcmp(evt.NewValue.String,' Before profil')
        obj.state =  'before';
      else
        obj.state =  'after';
      end
    end
    
    function selectPath(obj)
      obj.path = uigetdir();
      % when cancel is pressed uigetdir return 0
      if obj.path == 0; obj.path = []; end
      set(obj.hdlPath, 'string', obj.path);
    end
    
    function selectXmlFile(obj)
      [FileName,PathName] = uigetfile('*.xml','Select Seabird xml file');
      obj.xmlFile = fullfile(PathName, FileName);
      % when cancel is pressed uigetfile return 0
      if obj.xmlFile == 0; obj.xmlFile = []; end
      set(obj.hdlXmlFile, 'string', obj.xmlFile);
    end
    
    function selectCtdHeight(obj, src)
      obj.ctdHeight =  str2double(get(src, 'string'));
    end
    
    function selectBaroHeight(obj, src)
      obj.baroHeight =  str2double(get(src, 'string'));
    end
    
    % menu option for serial ports, CTD and barometric heigth
    % open new figure for configuration
    function menuOptions(obj)
      % define window aera
      f = get(obj.hdlMainFigure,'Position');
      % create new figure
      obj.hdlOptions = figure(...
        'Name', 'Options', ...
        'NumberTitle', 'off', ...
        'Resize', 'on', ...
        'Menubar','none', ...
        'Toolbar', 'none',...
        'Visible', 'on',...
        'WindowStyle', 'modal',...
        'Position',[f(1),f(2)+f(4)/2,f(3),f(4)/2], ...
        'Color', get(0, 'DefaultUIControlBackgroundColor'));
      
      % Tile for CTD serial port
      uicontrol ( obj.hdlOptions ,...
        'Style' , 'Text' ,...
        'String' ,'CTD - SBE911+' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'center',...
        'Position' ,[0.05 0.88 0.2 0.10],...
        'FontWeight', 'bold',...
        'FontSize',10);
      
      % Serial port
      uicontrol ( obj.hdlOptions ,...
        'Style' , 'Text' ,...
        'String' ,'Port' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.05 0.78 0.1 0.1],...
        'FontWeight', 'bold',...
        'FontSize',9);
      
      obj.hdlSelectPort = uicontrol ( obj.hdlOptions ,...
        'Style' , 'popup' ,...
        'String' , obj.portString ,...
        'Value', obj.port,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.15 0.79 0.1 0.1],...
        'callback', {@(src,evt) selectPort(obj,src)});
      
      uicontrol ( obj.hdlOptions ,...
        'Style' , 'Text' ,...
        'String' ,'Baudrate' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.05 0.63 0.1 0.1],...
        'FontWeight', 'bold',...
        'FontSize',9 );
      
      obj.hdlSelectBaudrate = uicontrol ( obj.hdlOptions ,...
        'Style' , 'popup' ,...
        'String' ,obj.baudRateString,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.15 0.64 0.1 0.1],...
        'Value',obj.baudRate,...
        'callback', {@(src,evt) selectBaudRate(obj,src)});
      
      uicontrol ( obj.hdlOptions ,...
        'Style' , 'Text' ,...
        'String' ,'Databits' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.05 0.48 0.1 0.1],...
        'FontWeight', 'bold',...
        'FontSize',9 );
      
      obj.hdlSelectDatabits = uicontrol ( obj.hdlOptions ,...
        'Style' , 'popup' ,...
        'String' , obj.dataBitsString ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Value',obj.dataBits,...
        'Position' ,[0.15 0.49 0.1 0.1],...
        'callback', {@(src,evt) selectDataBits(obj,src)}) ;
      
      uicontrol ( obj.hdlOptions ,...
        'Style' , 'Text' ,...
        'String' ,'Stopbits' , ...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position', [0.05 0.33 0.1 0.1],...
        'FontWeight', 'bold',...
        'FontSize',9 );
      
      obj.hdlSelectStopbits = uicontrol ( obj.hdlOptions ,...
        'Style' , 'popup' ,...
        'String' , obj.stopBitsString ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Value',obj.stopBits,...
        'Position' ,[0.15 0.34 0.1 0.1],...
        'callback', {@(src,evt) selectStopBits(obj,src)});
      
      uicontrol ( obj.hdlOptions ,...
        'Style' , 'Text' ,...
        'String' ,'Parity' , ...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position', [0.05 0.18 0.1 0.1],...
        'FontWeight', 'bold',...
        'FontSize',9 );
      
      obj.hdlSelectParity = uicontrol ( obj.hdlOptions ,...
        'Style' , 'popup' ,...
        'String' , obj.parityString ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Value',obj.parity,...
        'Position' ,[0.15 0.19 0.1 0.1],...
        'callback', {@(src,evt) selectParity(obj,src)});
      
      uicontrol ( obj.hdlOptions ,...
        'Style' , 'Text' ,...
        'String' ,'Terminator' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.05 0.03 0.1 0.1],...
        'FontWeight', 'bold',...
        'FontSize',9 );
      
      obj.hdlSelectTerminator = uicontrol ( obj.hdlOptions ,...
        'Style' , 'popup' ,...
        'String' , obj.terminatorString,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Value',obj.terminator,...
        'Position' ,[0.15 0.04 0.1 0.1],...
        'callback', {@(src,evt) selectTerminator(obj,src)} );
      
      % Title for SBE35 serial port
      uicontrol ( obj.hdlOptions ,...
        'Style' , 'Text' ,...
        'String' ,'SBE35' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'center',...
        'Position' ,[0.35 0.88 0.2 0.10],...
        'FontWeight', 'bold',...
        'FontSize',10);
      
      % Serial port for Sbe35
      uicontrol ( obj.hdlOptions ,...
        'Style' , 'Text' ,...
        'String' ,'Port' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.35 0.78 0.1 0.1],...
        'FontWeight', 'bold',...
        'FontSize',9);
      
      obj.hdlSelectPortSbe35 = uicontrol ( obj.hdlOptions ,...
        'Style' , 'popup' ,...
        'String' , obj.portString ,...
        'Value', obj.portSbe35,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.45 0.79 0.1 0.1],...
        'callback', {@(src,evt) selectPortSbe35(obj,src)});
      
      uicontrol ( obj.hdlOptions ,...
        'Style' , 'Text' ,...
        'String' ,'Baudrate' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.35 0.63 0.1 0.1],...
        'FontWeight', 'bold',...
        'FontSize',9 );
      
      obj.hdlSelectBaudrateSbe35 = uicontrol ( obj.hdlOptions ,...
        'Style' , 'popup' ,...
        'String' ,obj.baudRateString,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.45 0.64 0.1 0.1],...
        'Value',obj.baudRateSbe35,...
        'callback', {@(src,evt) selectBaudRateSbe35(obj,src)});
      
      uicontrol ( obj.hdlOptions ,...
        'Style' , 'Text' ,...
        'String' ,'Databits' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.35 0.48 0.1 0.1],...
        'FontWeight', 'bold',...
        'FontSize',9 );
      
      obj.hdlSelectDatabitsSbe35 = uicontrol ( obj.hdlOptions ,...
        'Style' , 'popup' ,...
        'String' , obj.dataBitsString ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Value',obj.dataBitsSbe35,...
        'Position' ,[0.45 0.49 0.1 0.1],...
        'callback', {@(src,evt) selectDataBitsSbe35(obj,src)}) ;
      
      uicontrol ( obj.hdlOptions ,...
        'Style' , 'Text' ,...
        'String' ,'Stopbits' , ...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position', [0.35 0.33 0.1 0.1],...
        'FontWeight', 'bold',...
        'FontSize',9 );
      
      obj.hdlSelectStopbitsSbe35 = uicontrol ( obj.hdlOptions ,...
        'Style' , 'popup' ,...
        'String' , obj.stopBitsString ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Value',obj.stopBitsSbe35,...
        'Position' ,[0.45 0.34 0.1 0.1],...
        'callback', {@(src,evt) selectStopBitsSbe35(obj,src)});
      
      uicontrol ( obj.hdlOptions ,...
        'Style' , 'Text' ,...
        'String' ,'Parity' , ...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position', [0.35 0.18 0.1 0.1],...
        'FontWeight', 'bold',...
        'FontSize',9 );
      
      obj.hdlSelectParitySbe35 = uicontrol ( obj.hdlOptions ,...
        'Style' , 'popup' ,...
        'String' , obj.parityString ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Value',obj.paritySbe35,...
        'Position' ,[0.45 0.19 0.1 0.1],...
        'callback', {@(src,evt) selectParitySbe35(obj,src)});
      
      uicontrol ( obj.hdlOptions ,...
        'Style' , 'Text' ,...
        'String' ,'Terminator' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.35 0.03 0.1 0.1],...
        'FontWeight', 'bold',...
        'FontSize',9 );
      
      obj.hdlSelectTerminatorSbe35 = uicontrol ( obj.hdlOptions ,...
        'Style' , 'popup' ,...
        'String' , obj.terminatorString,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Value',obj.terminatorSbe35,...
        'Position' ,[0.45 0.04 0.1 0.1],...
        'callback', {@(src,evt) selectTerminatorSbe35(obj,src)} );
      
      % Title for env parameters
      uicontrol ( obj.hdlOptions ,...
        'Style' , 'Text' ,...
        'String' ,'Env params' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'center',...
        'Position' ,[0.65 0.88 0.2 0.10],...
        'FontWeight', 'bold',...
        'FontSize',10);
      
      % CTD Height
      uicontrol ( obj.hdlOptions ,...
        'Style' , 'Text' ,...
        'String' ,'CTD height' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.65 0.78 0.1 0.1],...
        'FontWeight', 'bold',...
        'FontSize',9);
      
      obj.hdlSelectCtdHeight = uicontrol ( obj.hdlOptions ,...
        'Style' , 'edit' ,...
        'String' , num2str(obj.ctdHeight),...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.77 0.82 0.1 0.07],...
        'callback', {@(src,evt) selectCtdHeight(obj,src)});
      
      uicontrol ( obj.hdlOptions ,...
        'Style' , 'Text' ,...
        'String' ,'Baro height' ,...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.65 0.63 0.1 0.1],...
        'FontWeight', 'bold',...
        'FontSize',9 );
      
      obj.hdlSelectBaroHeight = uicontrol ( obj.hdlOptions ,...
        'Style' , 'edit' ,...
        'String' ,num2str(obj.baroHeight),...
        'units', 'normalized', ...
        'HorizontalAlignment', 'left',...
        'Position' ,[0.77 0.66 0.1 0.07],...
        'callback', {@(src,evt) selectBaroHeight(obj,src)});
    end
    
    % start acquisition
    function startAcquisition(obj, src)
      
      if isempty(obj.pressureBaro) || isempty(obj.tAir)
        msgbox({'You must enter values for : ', ...
          'Barometric pressure and Air temperature'}, 'Missing entries');
        return
      end
      % get serial port parameters from uicontrol choices
      % change button text
      if get(src, 'userdata') == false
        set(src,'BackgroundColor', 'y');
        set(src, 'String', 'Initializing...');
        set(src, 'UserData', true);
        
        % get serial port values from popup indice
        theSerialPort = obj.portString{obj.port};
        theBaudRate = str2double(obj.baudRateString{obj.baudRate});
        theDataBits = str2double(obj.dataBitsString{obj.dataBits});
        theStopBits = str2double(obj.stopBitsString{obj.stopBits});
        theParity = obj.parityString{obj.parity};
        theTerminator = obj.terminatorString{obj.terminator};
        
        % Start acquisition
        ctd = us191.ctd(obj.xmlFile,theSerialPort,'baudrate',theBaudRate,...
          'databits', theDataBits, 'stopbits', theStopBits, ...
          'parity', theParity, 'terminator',theTerminator);
        
        % define ctd files as path\station_[before|after].ext
        ctd.rawFileName = strcat(obj.path,filesep,...
          obj.station, strcat('_',obj.state), '.hex');
        ctd.dataFileName = strcat(obj.path,filesep,...
          obj.station, strcat('_',obj.state), '.cnv');
        
        % add listener
        obj.dataListenerHandle = addlistener(ctd,'dataAvailable',@obj.dataEvnt);
        
        % open serial port and send commands to the deck-unit
        ctd.open;
        
        % initialize ring for result
        obj.ringFinal = ring(obj.delay);
        
        % start the timer and callback for acquisition
        t = timer('name','timerFinal');
        t.StartDelay = obj.delay;
        t.TimerFcn = {@obj.stopAcquisition, src, ctd};
        t.StartFcn = {@obj.changeButtonStartToGreen, src};
        t.StopFcn = {@obj.changeButtonStartToRed, src};
        start(t);
        % start timer for averaging data from DU every second
        obj.timerAvg = timer('name','timerAverage',...
          'period',1,'StartDelay',1,'ExecutionMode','fixedRate');
        obj.timerAvg.TimerFcn = {@obj.getFromRingAvg};
        start(obj.timerAvg);
      end
    end
    
    % stop acquisition
    function stopAcquisition(obj,t,~,src, ctd)
      set(src, 'UserData', false);
      fprintf(1,'timer elapsed after delay: %d sec\n', obj.delay);
      % stop acquisition timer (from obj.delay)
      stop(t);
      delete(t);
      stop(obj.timerAvg);
      delete(obj.timerAvg);
      close(ctd);
      delete(obj.dataListenerHandle);
      compute(obj.ringFinal);
      med = obj.ringFinal.getMedian;
      stdev = obj.ringFinal.getStd;
      avg = obj.ringFinal.getAverage;
      var = obj.ringFinal.getVariance;
      % debug compute
      % baro= 1008.6;  Tair=28.1; H_ctd=3.5; H_baro=7.8;
      % med= 0.0; offest = -0.04;
      offset = computePressureOffset(obj, med);
      % display value on UiControls
      set(obj.hdlMedian, 'string', num2str(med));
      set(obj.hdlStandDev, 'string', num2str(stdev));
      set(obj.hdlMean, 'string', num2str(avg));
      set(obj.hdlVar, 'string', num2str(var));
      set(obj.hdlOffset, 'string', num2str(offset));
      % construct file name (.asc)
      obj.statFileName = strcat(obj.path,filesep, obj.station, '.asc');
      
      % save data on statistic file (.asc)
      if exist(obj.statFileName, 'file')
        fid = fopen(obj.statFileName, 'a+');
      else
        fid = fopen(obj.statFileName, 'w');
        fprintf(fid, ['Station    Date              State Timer Median ',...
          'Mean StdDevVariance Patm  Tair  Offset\n']);
      end
      fprintf(fid,'%s %s %6s %2d %5.2f %5.2f %5.3f %5.3f %6.1f  %4.1f %5.2f\n', ...
        obj.station, datestr(now), obj.state, obj.delay,...
        med, avg, stdev, var, obj.pressureBaro, obj.tAir, offset );
      fclose(fid);
    end % end of stopAcquisition
    
    % TODOS: change on anonymous function
    function changeButtonStartToGreen(obj,t,~,src) %#ok<INUSL>
      set(src,'BackgroundColor', 'g');
      set(src, 'String', 'Running...');
    end
    
    % TODOS: change on anonymous function
    function changeButtonStartToRed(obj,t,~,src) %#ok<INUSL>
      set(src,'BackgroundColor', 'r');
      set(src, 'String', 'Start');
    end
    
    % every second, get median value from DU and put to ring
    function getFromRingAvg(obj,~,~)
      compute(obj.ringAvg);
      % debug
      disp(obj.ringAvg.getAverage);
      % display median and mean value every seconde on UiControls
      set(obj.hdlMedian, 'string', num2str(obj.ringAvg.getMedian));
      set(obj.hdlMean, 'string', num2str(obj.ringAvg.getAverage));
      % put every second median value to ringFinal
      obj.ringFinal.put(obj.ringAvg.getMedian);
      %disp(obj.ringFinal.data)
    end
    
    % call from close figure
    function s = saveConfig(obj)
      
      % save properties value in a struct
      for prop = obj.propertiesToSave
        p = char(prop);
        s.(p) = obj.(p);
      end
      
      % save to mat file
      save( obj.configFile, 's', '-v7.3')
      
    end % end of saveConfig
    
    % restore the configuration from user.mat
    function loadConfig(obj)
      
      % test if configFile exist
      if exist(obj.configFile, 'file') == 2
        % load properties values from struct
        load(obj.configFile, 's');
        % if there no field VERSION or different version, initialize the
        % preference file .mat to default
        if ~(isfield(s, 'VERSION') && strcmp(s.VERSION,obj.VERSION))
          return
        end
        % set properties form propertiesToSave list
        for prop = obj.propertiesToSave
          p = char(prop);
          obj.(p) = s.(p);
        end
      end
      
    end % end of loadConfig
    
    % computePressureOffset calculate offset for SeaBird pressure sensor
    % in dbar from reference barometer
    % example to test offset computation:
    % a = acquisition
    % a.computePressureOffset(0.5);
    %
    function offset = computePressureOffset(obj, ctdPressure)
      
      % display on console input CTD pressure 
      fprintf(1, 'CTD pressure = %5.2f\n', ctdPressure);
      
      % Environment      
      P_baro = obj.pressureBaro; % atmospheric pressure in mbar from barometer
      T_air =  obj.tAir;   % air temperature in °C
      
      % Ship
      H_baro = obj.baroHeight;    % altitude barometer in meter
      H_CTD =  obj.ctdHeight;    % altitude CTD in meter
      
      % Constants
      %       g        = 9.806;         % standard gravity
      %       R        = 287.08;        % dry air constant
      K        = 273.15;        % °C to Kelvin conversion
      Ap       = 14.7;          % approximate atmospheric pressure at sea level in psi
      C        = 0.689476;      % factor conversion in dbar/psi
      
      % compute
      % atmospheric pressure at sea level in dbar (Meteo-France)
      P_atm    = (P_baro + ((P_baro * H_baro) / (29.2 * (T_air + K)))) * 0.01;
      % CTD absolute pressure from seabird relative pressure in dbar
      P_CTDa   = ctdPressure + (Ap * C);
      % CTD absolute pressure at sea level in dbar (Meteo-France)
      P_CTDa0  = (P_CTDa + ((P_CTDa * H_CTD) / (29.2 * (T_air + K))));
      
      % SeaBird pressure sensor offset
      offset   = P_atm - P_CTDa0;
      offset = round(offset*100)/100;
      
      % display on console offset CTD pressure 
      fprintf(1, 'Offset = %5.2f\n', offset);
    end    
    
  end % end of public methods
  
  methods (Access = private)
    
    % wait for dataAvalaible event from CTD
    function dataEvnt(obj,~,evnt)
      set(obj.hdlPressure, 'string', num2str(evnt.pressure));
      set(obj.hdlTemperature, 'string', num2str(evnt.temperature));
      set(obj.hdlModulo, 'string', num2str(evnt.modulo));
      set(obj.hdlFrequency, 'string', sprintf('%9.3f',evnt.frequency));
      % put value to ring buffer
      obj.ringAvg.put(evnt.pressure)
      %disp(obj.ringAvg.data);
    end
    
  end % end of private methods
  
end % ond of class

